### PR TITLE
Add categories

### LINKED ISSUE #37: [Idea] introduce Cart items categories
JSON file can contain new item field called categories:

`"categories": ["drink", "alcohol"],`

which would lead to categories button above the filter search where a person can quick-select the item category.

One item can be present in more categories.

### PR DESCRIPTION
**Pull request by talvasconcelos**
Add categories to products and filtering by category

Closes #37

### CODE REVIEW

**Comment by prusnak** [comment]
I found two issues:
- one in categories itself - if categories were not set, the attempt to create a new TPOS failed - this is addressed in b4c87b3ec8029c3da3d472bbc68a3f4a90e126da (which also modifies the Categories editor to behave exactly like the Tip editor - it uses the same attrs passed to `q-select` now)
- filtering was wrong - if no categoryFilter was given, the searchTerm stopped working - this is addressed in 8d7ee8bca62bfa65d4e3cb488dde2ec634df2921 which refactors the `filteredItems` function

**Comment by talvasconcelos** [comment]
Tested and all works as intended. Thank you for your input @prusnak

**Review by prusnak — APPROVED** [review]

**Review by motorina0 — APPROVED** [review]
utACK

**Review by dni — APPROVED** [review]
utACK

**Pull request merged**
