### PR TITLE
Added Fee to TPOS

### PR DESCRIPTION
**Pull request by KiddoKodes**
Hey,

I have added a fee field to the tpos extension so now folks can charge their users for using their tpos service. The feature is optional and defaults to 0% fees. The user gets charged x% more in sats and the extra gets stored in the main wallet.

### CODE REVIEW

**Comment by arcbtc** [comment]
I want to add but threw an error amount didn't seem to represent `amount + (amount * fee)`, and you are trying to add to the create_invoice field 
image
Add `amount + (amount * fee)`  in tpos.html where sat price gets computed and just include as the actual amount when you request the invoice

**Comment by KiddoKodes** [comment]
What was the error? Right now the amount gets calculated along the fee in tpos.html and is sent to invoices route

**Comment by dadofsambonzuki** [comment]
Interesting, fee added to the payer and not by the merchant.

I guess this is simply included in the sats amount as presented to the payer?

It would be good if you could set a target wallet for the fee to be paid to rather than just going to the target wallet of the TPOS.

So when setting up a TPOS you would be able to set targets for principle, tip and service fee.

**Comment by prusnak** [comment]
Do we still need this now that LNbits has global service fee?

**Comment by dadofsambonzuki** [comment]
Probably still useful to be able to set this on a per PoS basis to suit local markets rather than a singular global fee.

I think having both options is good.

**Comment by DoktorShift** [comment]
> Do we still need this now that LNbits has global service fee?

The global lnbits fee is great to settle a fee base for using the server/service.

This proposal allows you to negotiate more precise conditions with your future customers (If they use TPoS),

**Comment by prusnak** [comment]
Needs rebase

**Comment by arcbtc** [comment]
Tried to fix conflicts, but was too messy, so closing. PR is only a small one and could be added again.

**Pull request closed without merging**
