### PR TITLE
add a premium to ATM rate

### PR DESCRIPTION
**Pull request by talvasconcelos**
Add a premium % to ATM exchange rate

### CODE REVIEW

**Comment by motorina0** [comment]
Please add a test scenario (with testing steps). I'm not sure what these changes are supposed to do.

**Review by prusnak — APPROVED** [review]
utACK

**Comment by talvasconcelos** [comment]
> Please add a test scenario (with testing steps). I'm not sure what these changes are supposed to do.

Basically add a % premium to sell bitcoin from the ATM functionality. That percentage will be added to the exchange rate.

- create/edit Tpos with ATM option
- add your prefered premium in %
- sell btc with ATM mode
- value should be calculated with (exchange rate + premium)

**Review by arcbtc — APPROVED** [review]
🤌 Perfect

**Pull request merged**
