### PR TITLE
Functionality to add on TPoS

### LINKED ISSUE #28: Idea: add plus (+) functionality
Similar to https://github.com/btcpayserver/btcpayserver/issues/5299

We could easily add a new `+` button if we split the OK button into two halves and make the top half `+` and keep the bottom half `OK`:

Screenshot 2023-11-03 at 21 05 45

This would help tremendously for people who want to add prices of two products together and don't have a separate calculator.

### LINKED ISSUE #29: Idea: use different colors for POS buttons
There are different type of buttons:
- neutral - numbers and  Plus (see https://github.com/lnbits/tpos/issues/28)
- negative - backspace and delete (backspace being less negative than delete)
- positive - OK

So maybe we should use different colors for them. Such as:

280404768-b387ee30-6951-4775-98d5-3bd589f6c389

Of course, we should pick the colors from the theme and not use the hardcoded ones.

### PR DESCRIPTION
**Pull request by talvasconcelos**
Closes #28, closes #29

### CODE REVIEW

**Review by dni — APPROVED** [review]
try to make a seperate commit for formatting next time :) as it is easier to review. 
LGTM

**Review by prusnak — CHANGES_REQUESTED** [review]
1. Orange and Red colors are the other way around (DEL should be yellow since it deletes only 1 char, C should be red since it deletes all).
2. Plus functionality behaves super confusing - the OK should be always OK, the plus should be always +.
3. There is a merge conflict now.


PS: I think we should also swap positions of DEL and C (so C is left and DEL is right). Ideally also replace "DEL" with back arrow symbol (← or ⬅).

**Comment by prusnak** [comment]
Here's the patch that addresses point 1 and PS from my comment above:

``` patch
diff --git a/templates/tpos/tpos.html b/templates/tpos/tpos.html
index 1b6c11f..72efcd8 100644
--- a/templates/tpos/tpos.html
+++ b/templates/tpos/tpos.html
@@ -110,12 +110,12 @@
             >
             <q-btn
               unelevated
-              @click="stack.pop()"
+              @click="adding ? cancelAddAmount() : stack = []"
               size="xl"
               :outline="!($q.dark.isActive)"
               rounded
               color="negative"
-              >DEL</q-btn
+              >C</q-btn
             >
             <q-btn
               unelevated
@@ -128,13 +128,13 @@
             >
             <q-btn
               unelevated
-              @click="adding ? cancelAddAmount() : stack = []"
+              @click="stack.pop()"
               size="xl"
               :outline="!($q.dark.isActive)"
               rounded
               color="warning"
               class="btn-cancel"
-              >C</q-btn
+              >⬅</q-btn
             >
             <q-btn
               unelevated
```

**Comment by prusnak** [comment]
I also reworked the plus functionality, have a look at the branch [`add_plus_functionality-stick`](https://github.com/lnbits/tpos/tree/add_plus_functionality-stick). I think it is less confusing that way.

My branch is still just the UI prototype to show how I think the UI should work. Submitting the form still needs fixing (it should pickup `this.totalsat` instead of `this.sat` if `this.total > 0.0`).

**Review by prusnak — APPROVED** [review]
tested ACK

**Comment by talvasconcelos** [comment]
Can we get this merged on main? I need to work on something on top of it!

@dni @motorina0 ?

**Comment by prusnak** [comment]
> Can we get this merged on main? I need to work on something on top of it!

You have to resolve conflicts with main first. Then we can merge.

**Comment by talvasconcelos** [comment]
> > Can we get this merged on main? I need to work on something on top of it!
> 
> You have to resolve conflicts with main first (ideally with `git rebase main`). Then we can merge.

i don't see conflicts...

**Comment by prusnak** [comment]
> i don't see conflicts...

Because you did not pull main?

```
git checkout main
git pull
git checkout add_plus_functionality
git rebase main
```

**Comment by talvasconcelos** [comment]
> > i don't see conflicts...
> 
> Because you did not pull main?
> 
> ```
> git checkout main
> git pull
> git checkout add_plus_functionality
> git rebase main
> # ... fix conflicts
> git push --force
> ```

Nothing to rebase... (maybe you're seeing your branch `...-stick` ?)

no conflicts

**Comment by prusnak** [comment]
> Nothing to rebase...

Ah, OK. Squashing is possible via UI, rebasing via UI is not. Let's go and merge via squash! 👍

**Pull request merged**
